### PR TITLE
Allow whitelist userAgent by site

### PR DESCRIPTION
**Pull request by thelittlefireman**
#61  #84

### CODE REVIEW

**Comment by thelittlefireman** [comment]
If you would like to test it :

```
docker build -t nginx_uawhitelist .
```

Whitout whitelist

```
docker run --rm -p 80:8080 -e SERVER_NAME=mydomain.com -e BLOCK_USER_AGENT=yes nginx_uawhitelist
```

With whitelist

```
docker run --rm -p 80:8080 -e SERVER_NAME=mydomain.com -e BLOCK_USER_AGENT=yes -e "WHITELIST_USERAGENT_LIST=\"CCBot\"" nginx_uawhitelist
```

```
# Allow despite is in https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-user-agents.list
curl -H "User-Agent: CCBot" http://127.0.0.1:80

# Still deny (Bolt present in https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-user-agents.list)
curl -H "User-Agent: Bolt" http://127.0.0.1:80
```

Result
```
2021/02/03 11:49:05 [warn] 22986#22986: *1 [lua] access_by_lua(main-lua.conf:180):94: [BLOCK] User-Agent Bolt is blacklisted, client: 172.17.0.1, server: mydomain.com, request: "GET / HTTP/1.1", host: "127.0.0.1"

...
2021/02/03 11:49:38 [warn] 22986#22986: *4 [lua] access_by_lua(main-lua.conf:180):88: [ALLOW] User-Agent CCBot is whitelisted, client: 172.17.0.1, server: mydomain.com, request: "GET / HTTP/1.1", host: "127.0.0.1"

```

**Comment by thelittlefireman** [comment]
up ? :smiley: @bunkerity

**Comment by bunkerity** [comment]
Hello @thelittlefireman 

I think we can make it easier and more consistent with the existing work by simply removing the checks in LUA and generating a map-user-agent.conf like that : 

```
map $http_user_agent $bad_user_agent  {
  default no;
  ~*Agent1 no;
  ~*Agent2 no;
  ...
  ~*Agent1 yes;
  ~*Agent2 yes;
}
```

If we put the whitelisted UA at the beginning, nginx will stop on the first match so the mapped value will be a "no".

**Comment by thelittlefireman** [comment]
Hi,
Thanks for the reply. 
But we need to get a map-user-agent.conf per multisite ? And add a custom cron task for update on every multisite ?

**Comment by bunkerity** [comment]
You're right, copying the whole file for each site is not fine...

**Pull request merged**
